name: macos-next

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'macos-next/**'
      - '.github/workflows/macos-next.yml'
  workflow_dispatch:

jobs:
  components:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        test:
          - utilities/precheck
          - components/python
          - components/vscode
    steps:
      - uses: actions/checkout@v4
      - name: Show runner info
        run: |
          uname -a || true
          sw_vers || true
          which bash || true
          bash --version || true
      - name: Run component test
        run: |
          case "${{ matrix.test }}" in
            utilities/precheck)
              bash macos-next/tests/utilities/precheck.sh
              ;;
            components/python)
              bash macos-next/tests/components/python.sh
              ;;
            components/vscode)
              bash macos-next/tests/components/vscode.sh
              ;;
          esac

  build:
    runs-on: ubuntu-latest
    needs: components
    steps:
      - uses: actions/checkout@v4
      - name: Build single-file installer
        run: bash macos-next/tools/build.sh
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: macos-next-dist
          path: macos-next/dist/

  smoke:
    runs-on: macos-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Build and run integration dry-run
        run: |
          bash macos-next/tools/build.sh
          bash macos-next/tests/smoke.sh
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: macos-next-logs
          path: |
            /tmp/dtu_macos_next_*.log
            /tmp/macos_next_precheck_*.env
          if-no-files-found: ignore

  full:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: macos-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: bash macos-next/tools/build.sh
      - name: Full install (non-dry-run, no VS Code)
        run: |
          macos-next/dist/dtu-python-installer-macos.sh --yes
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: macos-next-full-logs
          path: |
            /tmp/dtu_macos_next_*.log
            /tmp/macos_next_precheck_*.env
          if-no-files-found: ignore
