name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.11

      - name: Install Constructor
        run: |
          conda install -c conda-forge constructor -y

      - name: Build Constructor Installer
        run: |
          echo "Building Constructor-based installer..."
          cd constructor_installer
          constructor --platform osx-64 .
          echo "Installer created:"
          ls -la *.pkg

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload PKG to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./constructor_installer/*.pkg
          asset_name: DTU_Python_Environment.pkg
          asset_content_type: application/octet-stream
