name: Windows_autoInstall

defaults:
  run:
    shell: pwsh

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Windows/**'
      - '.github/workflows/Windows_autoInstall.yml'
      - 'dev_plan_miniforge_windows.md'
  push:
    branches: [ "main" ]
    paths:
      - 'Windows/**'
      - '.github/workflows/Windows_autoInstall.yml'
      - 'dev_plan_miniforge_windows.md'

env:
  PYTHON_VERSION_PS: "3.11"
  PIS_ENV: "CI"

jobs:
  test-orchestrator:
    name: Test Windows First Year Orchestrator
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove conda (if present)
        run: |
          if (Get-Command conda -ErrorAction SilentlyContinue) {
            Write-Host "Base environment location:"
            conda info --base

            Write-Host "Removing conda from the environment..."
            # try and disable things in the boot-up scripts
            conda init --reverse --all
          }

          # Show PowerShell profiles
          $profilePaths = @($PROFILE.CurrentUserAllHosts, $PROFILE.CurrentUserCurrentHost)
          foreach ($profilePath in $profilePaths) {
            if (Test-Path $profilePath) {
              Write-Host "Profile: $profilePath"
              Get-Content $profilePath
            }
          }

      - name: Check for conda
        run: |
          $env:Path -split ';' | Where-Object { $_ -like "*conda*" } | ForEach-Object { Write-Host "Conda path: $_" }
          if (Get-Command conda -ErrorAction SilentlyContinue) {
            Write-Host "Base environment location:"
            conda info --base
          } else {
            Write-Host "Conda not found..."
          }

          # Show PowerShell profiles
          $profilePaths = @($PROFILE.CurrentUserAllHosts, $PROFILE.CurrentUserCurrentHost)
          foreach ($profilePath in $profilePaths) {
            if (Test-Path $profilePath) {
              Write-Host "Profile: $profilePath"
              Get-Content $profilePath
            }
          }

      - name: Run Windows First Year Orchestrator and Verify
        env:
          REMOTE_PS: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name || github.repository }}
          BRANCH_PS: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref_name }}
          GITHUB_CI: true
        run: |
          Write-Host "Testing Windows First Year Orchestrator from: $env:REMOTE_PS/$env:BRANCH_PS"
          
          # Set execution policy
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
          
          # Run the orchestrator
          $orchestratorUrl = "https://raw.githubusercontent.com/$env:REMOTE_PS/$env:BRANCH_PS/Windows/Components/orchestrators/first_year_students.ps1"
          Invoke-Expression (Invoke-WebRequest -Uri $orchestratorUrl -UseBasicParsing).Content
          
          Write-Host "=== Verification Phase ==="
          
          # Verify VS Code
          Write-Host "Verifying VS Code..."
          code --version
          if ($LASTEXITCODE -ne 0) {
            Write-Host "VS Code not installed correctly"
            exit $LASTEXITCODE
          }
          
          # Verify conda
          Write-Host "Verifying conda..."
          conda --version
          if ($LASTEXITCODE -ne 0) {
            Write-Host "Conda not installed correctly"
            exit $LASTEXITCODE
          }
          
          # Some more conda output
          conda --version
          conda info --base
          
          # Verify python (3.11)
          Write-Host "Verifying Python..."
          $condaPythonPath = "C:\Users\$env:USERNAME\miniforge3\python.exe"
          & $condaPythonPath --version
          
          # Verify the installed Python version
          $EXPECTED_VERSION = "3.11"
          $INSTALLED_VERSION = (& $condaPythonPath --version 2>&1) -replace "Python ", ""
          if ($INSTALLED_VERSION -notlike "$EXPECTED_VERSION*") {
            Write-Host "Installed Python version ($INSTALLED_VERSION) does not match expected version ($EXPECTED_VERSION)"
            exit 1
          }
          Write-Host "Correct Python version $INSTALLED_VERSION is installed."
          
          # Verify Python package imports
          & $condaPythonPath -c "import pandas, scipy, statsmodels, uncertainties; print('Packages imported successfully')"
          if ($LASTEXITCODE -ne 0) {
            Write-Host "Failed to import Python packages"
            exit 1
          }

